spring:
  application:
    name: aerosync
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/aerosync
    username: aerosync_user
    password: aerosync_password
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always